spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: ***.**.**.***
    port: 6379
server:
  context-path: /sell
wechat:
  mpAppId: wx777f4f5e7f1ccef7
  mpAppSecret: ebb4f15df7e750a88777b8b9dd88f86c
  openAppId: x6ad144e54af67d87
  openAppSecret: 91a2dd6s38a2bbccfb7e9
  mchId: 1409146202
  mchKey: c976503d34ca432c601361f969fd8d85
  keyPath: /var/weixin_cert/h5.p12
  notifyUrl: http://sell.natapcc/sell/pay/notify
  templateId:
    orderStatus: e-Cqq67QxD6YNI41iRqawEYdFavW_7pc7LyEMb-yeQ

projectUrl:
  wechatMpAuthorize: http://sell.natapp4.cc
  wechatOpenAuthorize: http://sell.natapp4.cc
  sell: http://localhost:8080

logging:
  level:
    com.imooc.dataobject.mapper: trace
mybatis:
  mapper-locations: classpath:mapper/*.xml













































#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/sell
#    username: root
#    password: 123456
#server:
#  servlet:
#    context-path: /sell

#logging:
#  pattern:
#    console: "%d - %msg%n"
#  #path: /var/log/tocat/
#  file: /var/log/tomcat/sell.log
#  level:      #debug
#    com.imooc.SellApplicationTests: debug